openapi.yaml
=> marge wcafe-api-reference

app/openapi.yaml
=> remove store_name in GET pets

app/openapi.yaml
GET pets/{pet_id}を作成しました。確認・マージお願いします。
=> create GET pet by pet_id in openapi.yaml

app/openapi.yaml
POST /pets 作成しました。確認・マージお願いします。
（exampleは柴犬にしてみました）
=> create post pets in openapi.yaml

app/openapi.yaml
以下の修正・追加を実施
1. getのレスポンスを配列形式に修正
2. store_idを取得するgetのAPIを追加
3. URLのいらない｝を削除
=> modify_new_get_id

app/openapi.yaml
petsに以下を追加しました。確認・マージお願いします。
* species
* age
=> updata pets.(add age and species)

app/openapi.yaml
=> add_store_get_param

README.md, controller/pet_controller.go, db/db.go, main.go, server/server.go, service/pets_service.go
* importの修正
* READMEにclone方法記載
=> Fix import path

README.md, api/openapi.yaml, controller/pet_controller.go, service/pets_service.go
`POST pet`した際に`UUID`を自動生成して`POST`する。
=> updata post pet. (add UUID)

README.md, server/server_test.go
がばがばのUT追加
やってること
GETの場合200OKが帰ってくるかどうか。
POSTの場合201が帰ってくるかどうか
だけチェックしてます。
=> Add UT Sample

README.md, config/config.go, config/config.toml, db/db.go
=> Add Config

config/config.go
=> HotFix Add Config Path

entity/stores.go, entity/users.go
List系APIのリターンの要素名が大文字だったのを小文字に変更
=> Fix List name

api/openapi.yaml
petのPOSTとGET{pet_id}が誤っていたので修正しました。
storeのPATCHが誤っていたので修正しました。
=> Fix pet api and stores patch api.

controller/store_controller_test.go
関数名修正
EX)TestList → TestStoreList
=> fix method name in store_controller_test.go .

api/openapi.yaml, controller/user_controller.go, controller/user_controller_test.go, entity/users.go, go.sum, mocks/users_service.go, server/server.go, server/server_test.go, service/stores_service.go, service/users_service.go
- OpenAPI usersのPATCH追加
- GoでusersのPATCH実装
- コンフリクト解決
=> add PATCH users

server/server.go
=> HotFix CORS URL

api/openapi.yaml
- DevURLを一時的にec2 serverになおした
- 
-
=> Fix_DevURL

.github/workflows/go.yml
=> Docker build

.github/workflows/aws.yml, .github/workflows/go.yml
- GitHubActions にconfig修正の反映
- 
-
=> #86 fix config (GitHub Actions)

server/server.go
- healthcheckを"/health"で出来るように修正
- 
-
=> fix health check

config/config.toml, db/db.go, entity/pets.go, entity/stores.go, entity/users.go
- 主キー設定
- 外部キー設定
- NOT　NULL　設定
=> change database

api/openapi.yaml
- GET stores/{store_id}のレスポンスを修正
- PATCH pets/{pet_id}
- POST users/
- PATCH users/
=> fix openapi.yaml GET store/store_id Response.

go.mod, go.sum, server/server_test.go
- server_test.goを修正
- POSTpetMethodにstore_idを取得する処理を追加
- POSTstoreMethodにnameの文字列を自動生成する処理を追加
=> fix server_test.go (POST pets & POST stores)

README.md
- READMEのSQS用コンフィグ設定部分の説明を追加
-
=> SQSのコンフィグ設定部分を追記

api/openapi.yaml, entity/pets.go, entity/stores.go, entity/users.go, service/pets_service.go, service/stores_service.go, service/users_service.go
- CreatedAtを追加
- UpdateAtを追加
-
=> Add CreatedAt UpdateAt.

api/openapi.yaml, controller/user_controller.go, controller/user_controller_test.go
- userのPATCHのステータスコードを修正（openapi.yamlに合わせた）
- updated_atのexampleが「"」で囲われてなかったので修正
-
=> fix http status code

README.md, config/config.go, config/config.toml, service/pets_service.go, service/stores_service.go
- POST store時にキューにメッセージを送信する処理の追加
- POST pet時にキューにメッセージを送信する際のログの修正
-
=> add stores sqs

api/openapi.yaml, controller/user_controller.go, controller/user_controller_test.go, go.mod, go.sum, mocks/users_service.go, server/server.go, service/users_service.go
- Userのエラー処理追加
- エラー処理用のController側のテストコードの作成
- Updateの404エラーのUTにバグがあるので別でバグチケ切ってます
　- user_controller_test.goのfunc TestUserUpdateNotFound(t *testing.T)部分
=> add Users error

api/openapi.yaml, controller/store_controller.go, controller/store_controller_test.go, mocks/stores_service.go, server/server.go, server/server_test.go, service/stores_service.go
- STORESのDELETE API設計
- STORESのDELETEメソッドの追加
- DELETE用のテストコードの作成
=> add stores DELETE Method

api/openapi.yaml, controller/pet_controller_test.go
=> POST pets/ add error(400).

entity/users.go, server/server_test.go, service/users_service.go
- users/の要素emailのvalidation check 機能を追加
- 上記のテストコード追加
-
=> Add validate email at users/

api/openapi.yaml, entity/pets.go
- petsのageの範囲を0～200に設定
- 上記に合わせてopenapiの追加
-
=> admit pets age 0

controller/pet_controller.go, controller/pet_controller_test.go, controller/store_controller.go, controller/store_controller_test.go, controller/user_controller_test.go, service/stores_service.go
- RecordNotFoundのエラー時の期待値404が400や409になってしまっていたテストコードバグを修正
- テストコードのimport部分を整形
-
=> record not foundのテスト修正

service/pets_service.go
- petsのPATCH時にrequiredの要素を指定しないとエラーが出ていたのを指定しなくても通るように修正
- 
-
=> petsのPATCH部分を修正

api/openapi.yaml, controller/pet_controller.go, controller/pet_controller_test.go, entity/pets.go, mocks/pets_service.go, server/server.go, service/pets_service.go
- petsのgorm repository対応
- petsのPATCHとDELETEのエラーに対するテストコードとAPI仕様の一部が不足していたため追加
-
=> gorm repository対応

controller/user_controller_test.go, entity/pets.go, entity/stores.go, entity/users.go, mocks/users_service.go, server/server.go, service/pets_service.go, service/stores_service.go, service/users_service.go
- usersとstoresのgorm repository化
- petsのrepository化の修正漏れをリファクタリング
-
=> petsとusersのgorm repository対応

config/config.toml, server/server.go
- config.tomlに本番環境（DBのエンドポイントとパスワード以外）の設定を記入
- gin.logを吐き出すパスを環境変数で変更できるように修正
-
=> write config & fix log path

server/server_test.go
- patchの準正常系テストを追加
- 各パラメータごとにvalidation指定と値が違うパターンを追加
- id指定で指定したidがないパターンを追加
=> add patch quasi-normal test

api/openapi.yaml, controller/supply_controller.go, controller/supply_controller_test.go, entity/supplies.go, mocks/supplies_service.go, protoc/supply.pb.go, protoc/supply.proto, server/server.go, server/server_test.go, service/supplies_service.go
- POST supplyを追加
- 上記のテスト作成
- server_test.goのPOSTテストを整理
=> Post supply

controller/clerk_conroller_test.go, controller/clerk_controller.go, entity/clerks.go, mocks/clerks_service.go, server/server.go, server/server_test.go, service/clerks_service.go
- POST /clerksの追加（DynamoDBを利用）
- 上記の正常系・準正常系テストの追加
-
=> #166 add post clerk

controller/store_controller_test.go
=> Add body check @ControllerTest

server/server_test.go, service/pets_service.go, service/stores_service.go, service/users_service.go
- POSTの準正常系テストの追加
- POST（Create）にvalidationチェック処理の追加
-
=> fix POST UT

controller/clerk_conroller_test.go, controller/clerk_controller.go, controller/pet_controller.go, controller/pet_controller_test.go, controller/store_controller.go, controller/store_controller_test.go, controller/supply_controller.go, controller/supply_controller_test.go, controller/user_controller.go, controller/user_controller_test.go, server/server_test.go
- net/httpを利用してステータスコードを定数化
- 
-
=> status codeの定数化

service/clerks_service.go, service/pets_service.go, service/stores_service.go, service/supplies_service.go
- POSTとPATCHにvalidationチェックを行う処理を追加
- 
-
=> Add validation check

entity/users_test.go
- entity/user.goの正常系テストを作成。
- 
-
=> User entity test

entity/users.go, entity/users_test.go, service/users_service.go
- validation処理を関数化し、entityに移行
- validtionの正常系・準正常系テストを追加
-
=> add subnormal test in user entity test.

README.md, controller/clerk_conroller_test.go, entity/clerks.go, service/clerks_service.go
- clerksのDynamoDBのテーブル名（clerks_name→clerks）とカラム（name_id→id）を変更
- 
-
=> fix clerks dynamodb

api/openapi.yaml
-  clerk delete openapi.yamlの更新（name_id ⇒id）
=> Clerk delete

api/openapi.yaml, entity/stores.go, entity/users.go, entity/users_test.go, service/pets_service.go, service/stores_service.go, service/users_service.go
- USERSとSTORESのDBにstatusのカラムを追加
- entityにstatusを追加
- serviceのstatus用に修正
- openapiにstatus欄追加
=> add STATUS column

server/server_test.go
- server_test実行時にDBのテーブルが空の状態でも動くように初期データ投入処理を追加
- 
-
=> add init table data

api/openapi.yaml, controller/clerk_controller.go, controller/clerk_controller_test.go, go.mod, go.sum, mocks/clerks_service.go, server/server.go, server/server_test.go, service/clerks_service.go
-  clerk update機能に関連する部分をopenapi.yamlに追加
=> add clerk-update function openapi.yaml
